# Generated by Django 2.1.1 on 2019-10-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
